### ISSUE TITLE
Create a page to exercise the API of another group

### ISSUE THREAD

**Issue by jlmao** [jadesym/cs373-idb#36]

**Comment by chanjoongkim** [comment]
Gonna start work on this. I'm thinking that we'll just have a page with a bunch of criteria that a user is looking for in a game.
Something like:
"Which platforms would you like the games to be on?"
"Is there a minimum rating the game must have?"
"Is there a minimum release date the game must have?"

Then we would return a list of all the games that fit the requirements.
